# Generated by Django 2.0.5 on 2018-08-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=64, unique=True)),
                ('ru_description', models.CharField(blank=True, max_length=128, null=True)),
                ('en_name', models.CharField(max_length=64, unique=True)),
                ('en_description', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ('ru_name',),
            },
        ),
        migrations.CreateModel(
            name='SportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=64)),
                ('ru_description', models.CharField(blank=True, max_length=128, null=True)),
                ('en_name', models.CharField(max_length=64)),
                ('en_description', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ('ru_name',),
            },
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ('ru_name',)},
        ),
        migrations.RemoveField(
            model_name='sport',
            name='name',
        ),
        migrations.AddField(
            model_name='sport',
            name='en_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='en_name',
            field=models.CharField(default='none', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='ru_description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='ru_name',
            field=models.CharField(default='none', max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporttype',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport'),
        ),
        migrations.AddField(
            model_name='sportgroup',
            name='sports',
            field=models.ManyToManyField(to='sports.Sport'),
        ),
    ]
