# Generated by Django 2.0.5 on 2018-08-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20180808_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportSubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru_name', models.CharField(max_length=64, unique=True)),
                ('ru_description', models.CharField(blank=True, max_length=128, null=True)),
                ('en_name', models.CharField(max_length=64, unique=True)),
                ('en_description', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ('ru_name',),
            },
        ),
        migrations.RemoveField(
            model_name='sportgroup',
            name='sports',
        ),
        migrations.AddField(
            model_name='sportsubgroup',
            name='sport_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.SportGroup'),
        ),
        migrations.AddField(
            model_name='sportsubgroup',
            name='sports',
            field=models.ManyToManyField(to='sports.Sport'),
        ),
    ]
